---
title: India Reforms
timezone: UTC
collections:
defaults:
permalink: pretty
email: IndiaStates@csis.org
description: Reformss
baseurl:
url: https://csis-india-reforms.netlify.com
date_format: "%B %-d, %Y"
post_meta_limit: 5
post_meta_sector_limit: 3
exclude:
