---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: NETLIFY.md
  label: Build Status
  read_only: true
- type: document
  path: src/content/homepage.md
  label: Top Text
- type: document
  path: src/content/footer.md
  label: Bottom Text
- type: document
  path: src/app/reforms.json
  label: REFORM DATA
- type: document
  path: ".forestry/sector.yml"
  label: Sectors
upload_dir: src/assets/images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
