# config.yml
local_backend: true

# live
backend:
  name: git-gateway
  # branch: master # Branch to update (optional; defaults to master)
  # branch: staging # Branch to update. Dev is now selected so we dont override any content that the program is adding.
  branch: development # Branch to update. Dev is now selected so we dont override any content that the program is adding.

media_folder: '_uploads'
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads
# publish_mode: 'editorial_workflow'
display_url: 'https://indiareforms.csis.org'
logo_url: 'https://raw.githubusercontent.com/CSIS-iLab/energy-database/main/public/android-chrome-192x192.png'
search: false
collections:
  - name: 'reforms'
    label: 'Reforms'
    label_singular: 'Reform'
    extension: json
    format: json
    create: false
    editor:
      preview: false
    files:      
      - label: "India Reforms"
        name: "india-reforms"
        # file: "public/india-reforms.json"
        file: "src/app/india-reforms.json"
        fields:
          - label: 'Reforms'
            name: 'reforms'
            label_singular: 'Reform'
            widget: 'list'
            add_to_top: true
            allow_add: true
            collapsed: true
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - label: 'Steps'
                name: 'steps'
                widget: 'object'
                collapse: true
                fields:
                  - label: 'Not Started'
                    name: 'not_started'
                    widget: 'object'
                    collapse: true
                    fields:
                      - {label: 'Status', name: 'status', widget: 'hidden', default: "Not Started", options: ["Not Started", "Incomplete", "Completed"], required: false}
                      - {label: 'Description', name: 'description', widget: 'text', required: false }
                      - {label: 'Link', name: 'link', widget: 'string', default: '', pattern: ['^(http|https)://', "Must start with https:// or http://"], required: false }
                  - label: 'Incomplete'
                    name: 'incomplete'
                    widget: 'object'
                    collapse: true
                    fields:
                      - {label: 'Status', name: 'status', widget: 'hidden', default: "Incomplete", options: ["Not Started", "Incomplete", "Completed"], required: false}
                      - {label: 'Description', name: 'description', widget: 'text', required: false}
                      - {label: 'Link', name: 'link', widget: 'string', default: '', pattern: ['^(http|https)://', "Must start with https:// or http://"], required: false}
                  - label: 'Completed'
                    name: 'completed'
                    widget: 'object'
                    collapse: true
                    fields:
                      - {label: 'Status', name: 'status', widget: 'hidden', default: "Completed", options: ["Not Started", "Incomplete", "Completed"], required: false}
                      - {label: 'Description', name: 'description', widget: 'text', required: false}
                      - {label: 'Link', name: 'link', widget: 'string', default: '', pattern: ['^(http|https)://', "Must start with https:// or http://"], required: false}
              - label: "Status"
                name: "status"
                widget: "select"
                default: "not_started"
                options: ["not_started", "incomplete", "completed"]
              - label: "Difficulty"
                name: 'difficulty'
                widget: 'select'
                options: ["low", "medium", "high"]
              # - label: "Sectors"
              #   name: 'sectors'
              #   required: false
              #   widget: 'hidden'
              #   options: []
              #   default: ''
                # options: ["market access", "infrastructure", "industry", "fiscal", "communications", "agriculture", "defense", "energy/mining", "retail", "services"]
